name: build-and-push-vault-auditor-binary-arm

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Darwin/ARM64 binary
      run: GOOS=darwin GOARCH=arm64 go build -o vault-auditor ./

    - name: Setup Docker on macOS
      uses: douglascamata/setup-docker-macos-action@v1-alpha
  

    - name: Build Docker image for Darwin/ARM64
      run: docker buildx build --no-cache --platform linux/arm64/v8 --file Dockerfile ./ -t ghcr.io/czembower/vault-auditor-arm64:latest

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Push images
      run: |
        docker push ghcr.io/czembower/vault-auditor-darwin-arm64:latest