name: build-and-push-vault-auditor-binary

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build vault-auditor binary
      run: GOOS=linux GOARCH=amd64 go build ./

    - name: Build Docker image
      run: docker build ./ -t ghcr.io/czembower/vault-auditor:latest

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Push image
      run: docker push ghcr.io/czembower/vault-auditor:latest